### ISSUE TITLE
Middlewares are not firing end/response triggers

### ISSUE THREAD

**Issue by DKunin** [rambler-digital-solutions/superagent-mocker#22]
If I attach a middleware to mocked superagent - whether I try to substitute an end callback, or have a trigger on 'end', 'response' events - nothing works. 
As soon as I unmock - everything works great.

MiddleWare example:

```
    var middlewareSuperagent = function(req) {
      console.log('STARTED');
      req._callback_orig = req.callback;
      req.callback = function(err, res) {  
        console.log('FINISHED');
        req._callback_orig(err, res);
      }
    };
```

**Comment by A** [comment]
Good catch! Thank you!

**Comment by leviwheatcroft** [comment]
Any progress on this ? It's a deal breaker for many use cases. 

I had a quick look at the situation, it looks like superagent [binds the events from the original response object](https://github.com/visionmedia/superagent/blob/b47a0112bc5d789e496f3f709a395125bf8537d7/lib/node/response.js#L46) I did try doing something similar where we patch Request.end() but couldn't get it to work, and couldn't figure out why. Sorry.

**Comment by DKunin** [comment]
@A Dude, is this still an issue, maybe the issue should be closed?
