### ISSUE TITLE
can't get query string

### ISSUE THREAD

**Issue by yalishizhude** [rambler-digital-solutions/superagent-mocker#27]
```
var obj = {id:1};
request.get('/a').query(obj).end();
```

In this  situation,mock only has headers,body and cannot get the variable "obj",can support it?

**Comment by pictin** [comment]
Same for me. Looks like code does not support superagent's query() at the moment.

**Comment by ra100** [comment]
I think this should be closed, issue has been already fixed.

**Comment by kmudrick** [comment]
As of version 0.5.0, superagent-mocker should capture query params: https://github.com/A/superagent-mocker/pull/35
