### ISSUE TITLE
Maybe it's a bug~

### ISSUE THREAD

**Issue by yalishizhude** [rambler-digital-solutions/superagent-mocker#28]
When superagent send two requests to one router path with diffrent request's body almost the same time.When the second request is sent while  mock is dealing with the first request,the first request's body will be overwriten by the second request's body.
For instance.

```
mock.get('/test', function(req){
  //logic code which costs CPU and long time
  console.log(req.body);
  //first request : {name:"b"}
  //seconde request: {name:"b"}
});

superagent.get('/test').send({name:'a'});
superagent.get('/test').send({name:'b'});
```

I tried to sovle this problem and it works:

```
//      setTimeout(function(s) {
        try {
          cb && cb(null, current(state.request));
        } catch (ex) {
          cb && cb(ex, null);
        }
//     }, value(mock.timeout), state);
```

I tried to fix it in this PR
https://github.com/A/superagent-mocker/pull/29

**Comment by serga-kiev** [comment]
PR merged
