### ISSUE TITLE
Invalid status check

### ISSUE THREAD

**Issue by HatiGamedev** [rambler-digital-solutions/superagent-mocker#33]
Status-Code: 201 (Created) should not throw an error but currently does, as just 200 is error free.

```
          if (response.status !== 200) {
            cb && cb(response, null);
          } else {
            cb && cb(null, response);
          }
```

Also, Regarding #9

**Comment by kmudrick** [comment]
@HatiEth this was fixed with https://github.com/A/superagent-mocker/pull/38 and released as 0.5.2
