### ISSUE TITLE
unmock takes an argument

### ISSUE THREAD

**Issue by j0hnsmith** [rambler-digital-solutions/superagent-mocker#41]
readme.md says to unmock with `mock.unmock()`, actually it's `mock.unmock(superagent)`.

https://github.com/A/superagent-mocker/blob/bc51d1e446ea1c9fac0f4aa46ed5ca622442f130/index.js#L170

**Comment by kmudrick** [comment]
@j0hnsmith if you'd like to create a PR to fix that in the Readme, we will gladly accept it and merge it in :)

**Comment by j0hnsmith** [comment]
@kmudrick done
